class MockDataGenerator {
  MockDataGenerator._();

  static List<Map<String, dynamic>> mockDevices = [
    {
      "mac": "AA:BB:CC:11:22:33",
      "name": "Ahmed iPhone",
      "ip": "192.168.1.12",
      "hostname": "Ahmed-iPhone",
      "usage_gb": 18.4,
      "quota_gb": 20.0,
      "remaining_gb": 1.6,
      "enabled": true,
      "is_blocked": false,
    },
    {
      "mac": "AA:BB:CC:22:33:44",
      "name": "Laptop",
      "ip": "192.168.1.15",
      "hostname": "ThinkPad-T14",
      "usage_gb": 12.1,
      "quota_gb": 15.0,
      "remaining_gb": 2.9,
      "enabled": true,
      "is_blocked": false,
    },
    {
      "mac": "11:22:33:44:55:66",
      "name": "Smart TV",
      "ip": "192.168.1.20",
      "hostname": "Samsung-4K-TV",
      "usage_gb": 8.9,
      "quota_gb": 10.0,
      "remaining_gb": 1.1,
      "enabled": true,
      "is_blocked": false,
    },
    {
      "mac": "3C:E5:A6:12:34:56",
      "name": "PS5",
      "ip": "192.168.1.25",
      "hostname": "PS5-Console",
      "usage_gb": 6.2,
      "quota_gb": 8.0,
      "remaining_gb": 1.8,
      "enabled": true,
      "is_blocked": false,
    },
    {
      "mac": "F4:BD:9E:01:23:45",
      "name": "Security Camera",
      "ip": "192.168.1.30",
      "hostname": "IPC-Outdoor-Front",
      "usage_gb": 4.8,
      "quota_gb": 5.0,
      "remaining_gb": 0.2,
      "enabled": true,
      "is_blocked": false,
    },
    {
      "mac": "00:1A:2B:3C:4D:5E",
      "name": "iPad Pro",
      "ip": "192.168.1.14",
      "hostname": "iPad-Pro-M2",
      "usage_gb": 4.2,
      "quota_gb": 10.0,
      "remaining_gb": 5.8,
      "enabled": true,
      "is_blocked": false,
    },
    {
      "mac": "70:85:C2:55:66:77",
      "name": "Work MacBook",
      "ip": "192.168.1.16",
      "hostname": "MacBook-Air",
      "usage_gb": 3.9,
      "quota_gb": 15.0,
      "remaining_gb": 11.1,
      "enabled": true,
      "is_blocked": false,
    },
    {
      "mac": "88:66:AA:BB:CC:DD",
      "name": "Kitchen Display",
      "ip": "192.168.1.35",
      "hostname": "Nest-Hub",
      "usage_gb": 2.1,
      "quota_gb": 5.0,
      "remaining_gb": 2.9,
      "enabled": true,
      "is_blocked": false,
    },
    {
      "mac": "12:34:56:78:9A:BC",
      "name": "Guest Phone",
      "ip": "192.168.1.50",
      "hostname": "Pixel-8",
      "usage_gb": 1.8,
      "quota_gb": 5.0,
      "remaining_gb": 3.2,
      "enabled": true,
      "is_blocked": false,
    },
    {
      "mac": "99:88:77:66:55:44",
      "name": "Smart Speaker",
      "ip": "192.168.1.60",
      "hostname": "Echo-Dot",
      "usage_gb": 1.2,
      "quota_gb": 3.0,
      "remaining_gb": 1.8,
      "enabled": true,
      "is_blocked": false,
    },
    {
      "mac": "55:44:33:22:11:00",
      "name": "Nintendo Switch",
      "ip": "192.168.1.65",
      "hostname": "Switch-OLED",
      "usage_gb": 2.5,
      "quota_gb": 8.0,
      "remaining_gb": 5.5,
      "enabled": true,
      "is_blocked": false,
    },
    {
      "mac": "CC:DD:EE:FF:00:11",
      "name": "Home Assistant",
      "ip": "192.168.1.200",
      "hostname": "ha-server",
      "usage_gb": 1.0,
      "quota_gb": 5.0,
      "remaining_gb": 4.0,
      "enabled": true,
      "is_blocked": false,
    },
    // Blocked Devices (3)
    {
      "mac": "66:77:88:99:AA:BB",
      "name": "Unknown Device",
      "ip": "192.168.1.45",
      "hostname": "unknown-intruder",
      "usage_gb": 0.5,
      "quota_gb": 0.0,
      "remaining_gb": 0.0,
      "enabled": false,
      "is_blocked": true,
    },
    {
      "mac": "44:55:66:77:88:99",
      "name": "Old Android Tablet",
      "ip": "192.168.1.72",
      "hostname": "android-tab-old",
      "usage_gb": 10.0,
      "quota_gb": 10.0,
      "remaining_gb": 0.0,
      "enabled": false,
      "is_blocked": true,
    },
    {
      "mac": "22:33:44:55:66:77",
      "name": "Blocked Tor Client",
      "ip": "192.168.1.99",
      "hostname": "anonymous-tor",
      "usage_gb": 1.2,
      "quota_gb": 1.0,
      "remaining_gb": 0.0,
      "enabled": false,
      "is_blocked": true,
    },
  ];

  static Map<String, dynamic> mockReport = {
    "status": "success",
    "total_bandwidth_used_gb": 68.0,
    "package_total_gb": 100.0,
    "package_remaining_gb": 32.0,
    "cycle_days_remaining": 12,
    "top_consumers": [
      {
        "mac": "AA:BB:CC:11:22:33",
        "name": "Ahmed iPhone",
        "ip": "192.168.1.12",
        "usage_gb": 18.4,
        "percentage": 27.0,
      },
      {
        "mac": "AA:BB:CC:22:33:44",
        "name": "Laptop",
        "ip": "192.168.1.15",
        "usage_gb": 12.1,
        "percentage": 18.0,
      },
      {
        "mac": "11:22:33:44:55:66",
        "name": "Smart TV",
        "ip": "192.168.1.20",
        "usage_gb": 8.9,
        "percentage": 13.0,
      },
      {
        "mac": "3C:E5:A6:12:34:56",
        "name": "PS5",
        "ip": "192.168.1.25",
        "usage_gb": 6.2,
        "percentage": 9.0,
      },
      {
        "mac": "F4:BD:9E:01:23:45",
        "name": "Security Camera",
        "ip": "192.168.1.30",
        "usage_gb": 4.8,
        "percentage": 7.0,
      },
    ]
  };

  static List<Map<String, dynamic>> mockActivities = [
    {
      "id": "act-1",
      "title": "Device unblocked",
      "device_description": "Laptop (192.168.1.15)",
      "timestamp": DateTime.now().subtract(const Duration(minutes: 18)).toIso8601String(),
      "type": "unblocked",
    },
    {
      "id": "act-2",
      "title": "Quota updated",
      "device_description": "Ahmed iPhone (192.168.1.12) → 20 GB",
      "timestamp": DateTime.now().subtract(const Duration(minutes: 30)).toIso8601String(),
      "type": "quotaUpdated",
    },
    {
      "id": "act-3",
      "title": "Device blocked",
      "device_description": "Unknown (192.168.1.45)",
      "timestamp": DateTime.now().subtract(const Duration(minutes: 46)).toIso8601String(),
      "type": "blocked",
    },
    {
      "id": "act-4",
      "title": "New device connected",
      "device_description": "iPhone (192.168.1.18)",
      "timestamp": DateTime.now().subtract(const Duration(minutes: 60)).toIso8601String(),
      "type": "connected",
    },
  ];
}
